---
- name: Create a website at AWS
  hosts: all
  become: true

  collections:
    - ansible.builtin
    - community.docker

  vars_files:
    - vars/vars.yml
    
  handlers:
    - import_tasks: handlers/main.yml
  
  tasks:
    - name: Configure server with Docker and dependencies
      include_tasks: config-server.yml

    - name: Create application directory
      file:
        path: "{{ app_install_dir }}"
        state: directory
        mode: '0755'